# Copyright 2017 Edward Diener
# Copyright 2018 Mike Dev
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

version: 1.0.{build}-{branch}

shallow_clone: true

configuration:
  - boost_test
  - cmake_self_test

branches:
  only:
    - master
    - develop

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      TOOLSET: msvc-9.0,msvc-10.0,msvc-11.0,msvc-12.0,msvc-14.0
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      TOOLSET: msvc-14.1

build: off

for:
-
  matrix:
    only:
      - configuration: cmake_self_test

  test_script:
    - mkdir __build__
    - cd __build__
    - cmake ../test
    - cmake --build .

-
  matrix:
    only:
      - configuration: boost_test

  install:
    - cd ..
    - git clone -b %APPVEYOR_REPO_BRANCH% https://github.com/boostorg/boost.git boost-root
    - cd boost-root
    - git submodule update --init tools/build
    - git submodule update --init libs/config
    - git submodule update --init tools/boostdep
    - git submodule update --init tools/boost_install
    - git submodule update --init libs/headers
    - xcopy /s /e /q %APPVEYOR_BUILD_FOLDER% libs\preprocessor
    - python tools/boostdep/depinst/depinst.py preprocessor
    - bootstrap
    - b2 headers

  test_script:
    - b2 libs/preprocessor/test toolset=%TOOLSET%
    - cd ../preprocessor/test

